#!/usr/bin/env bash
# PreToolUse (Edit|Write): deny edits to protected paths. Belt-and-braces on top of permissions.deny.
# Input: JSON on stdin with .tool_input.file_path. Output: JSON permissionDecision or exit 0 (no decision).
set -u
input=$(cat)
path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
[ -z "$path" ] && exit 0

deny() {
  jq -n --arg r "$1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

case "$path" in
  *"/.env"|*"/.env."*|*".env"|*".env."*) deny "Secrets file. Edit .env by hand; app reads it via backend/app/core/config.py." ;;
  *"/data/"*|"data/"*)                  deny "Runtime data (learner DB, backups, corpus). Never edited by Claude." ;;
  *"/alembic/versions/"*)
    # Migrations are generated by `make migrate`, not hand-written, unless the ADR skill says otherwise.
    printf '%s' "$input" | jq -e '.tool_name == "Write"' >/dev/null 2>&1 && \
      deny "Migrations are generated with 'make migrate m=\"...\"' (see /db-migration). Edit an existing one only to fix autogenerate output." ;;
  *"/docs/adr/"*)
    # ADRs are append-only once accepted; allow creating new ones, block rewriting accepted ones.
    if [ -f "$path" ] && grep -q '^Status: Accepted' "$path" 2>/dev/null; then
      deny "Accepted ADR is immutable. Write a new superseding ADR with /adr."
    fi ;;
esac
exit 0
