"""stage4 adaptation proposals

Revision ID: 064e2993cba7
Revises: 03c8da410c84
Create Date: 2026-09-19 17:10:56.850169

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "064e2993cba7"
down_revision: str | Sequence[str] | None = "03c8da410c84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adaptation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("pattern", sa.Text(), nullable=False, server_default=sa.text("''"))
        )
        batch_op.add_column(
            sa.Column("apply_json", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )
        batch_op.add_column(sa.Column("previous_json", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column("evidence_json", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )
        batch_op.add_column(sa.Column("session_id", sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f("ix_adaptation_session_id"), ["session_id"], unique=False)
        batch_op.create_foreign_key("fk_adaptation_session", "session", ["session_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adaptation", schema=None) as batch_op:
        batch_op.drop_constraint("fk_adaptation_session", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_adaptation_session_id"))
        batch_op.drop_column("session_id")
        batch_op.drop_column("evidence_json")
        batch_op.drop_column("previous_json")
        batch_op.drop_column("apply_json")
        batch_op.drop_column("pattern")

    # ### end Alembic commands ###
