"""db-core: all phase-1 tables

Revision ID: 08e0e269a737
Revises:
Create Date: 2026-09-19 12:21:58.955464

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.ddl import LEARNING_EVENT_GUARDS, drop_guard

# revision identifiers, used by Alembic.
revision: str = "08e0e269a737"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_rubric",
        sa.Column("criteria_json", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("course", sa.Text(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("lecture", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_course"), ["course"], unique=False)

    op.create_table(
        "index_state",
        sa.Column("collection", sa.Text(), nullable=False),
        sa.Column("embedding_registry_id", sa.Text(), nullable=False),
        sa.Column("embedding_version", sa.Integer(), nullable=False),
        sa.Column("dims", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("last_reindex", sa.Text(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection"),
    )
    op.create_table(
        "learner_profile",
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_registry",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("repo_id", sa.Text(), nullable=False),
        sa.Column("file_or_tag", sa.Text(), nullable=True),
        sa.Column("runtime", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("quant", sa.Text(), nullable=True),
        sa.Column("size_gb", sa.Float(), nullable=True),
        sa.Column("context_len", sa.Integer(), nullable=True),
        sa.Column("licence", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("benchmark_json", sa.JSON(), nullable=True),
        sa.Column("price_in_per_mtok", sa.Float(), nullable=False),
        sa.Column("price_out_per_mtok", sa.Float(), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column("added_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill_node",
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("success_criteria_json", sa.JSON(), nullable=False),
        sa.Column("assessment_requirements_json", sa.JSON(), nullable=False),
        sa.Column("example_applications_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("skill_node", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skill_node_domain"), ["domain"], unique=False)

    op.create_table(
        "adaptation",
        sa.Column("what", sa.Text(), nullable=False),
        sa.Column("why", sa.Text(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("reversible", sa.Boolean(), nullable=False),
        sa.Column("proposed_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adaptation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_adaptation_learner_id"), ["learner_id"], unique=False)

    op.create_table(
        "assessment",
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("item_json", sa.JSON(), nullable=False),
        sa.Column("rubric_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["assessment_rubric.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assessment_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "competency_state",
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("dimension", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("last_evidence_ts", sa.Text(), nullable=True),
        sa.Column("refreshed_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "skill_id", "dimension", name="uq_competency_state"),
    )
    with op.batch_alter_table("competency_state", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competency_state_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competency_state_skill_id"), ["skill_id"], unique=False
        )

    op.create_table(
        "document_version",
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("publication_date", sa.Text(), nullable=True),
        sa.Column("ingested_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "content_hash", name="uq_document_version_hash"),
    )
    with op.batch_alter_table("document_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_version_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_version_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "experiment",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("experiment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_experiment_learner_id"), ["learner_id"], unique=False)

    op.create_table(
        "learner_preference",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reversible", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "key", name="uq_learner_preference_key"),
    )
    with op.batch_alter_table("learner_preference", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learner_preference_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "learning_object",
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("concept", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("sources_json", sa.JSON(), nullable=False),
        sa.Column("examples_json", sa.JSON(), nullable=False),
        sa.Column("exercises_json", sa.JSON(), nullable=False),
        sa.Column("success_criteria_json", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("learning_object", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_learning_object_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "session",
        sa.Column("started_at", sa.Text(), nullable=False),
        sa.Column("ended_at", sa.Text(), nullable=True),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("socratic", sa.Boolean(), nullable=False),
        sa.Column("energy_after", sa.Integer(), nullable=True),
        sa.Column("planned_blocks_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_learner_id"), ["learner_id"], unique=False)

    op.create_table(
        "skill_edge",
        sa.Column("from_skill_id", sa.Text(), nullable=False),
        sa.Column("to_skill_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_skill_id"],
            ["skill_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_skill_id"],
            ["skill_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_skill_id", "to_skill_id", "kind", name="uq_skill_edge"),
    )
    with op.batch_alter_table("skill_edge", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_skill_edge_from_skill_id"), ["from_skill_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_skill_edge_to_skill_id"), ["to_skill_id"], unique=False
        )

    op.create_table(
        "adaptation_decision",
        sa.Column("adaptation_id", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.Text(), nullable=False),
        sa.Column("undone_at", sa.Text(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adaptation_id"],
            ["adaptation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adaptation_decision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_adaptation_decision_adaptation_id"), ["adaptation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_adaptation_decision_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "assessment_attempt",
        sa.Column("assessment_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("confidence_pre", sa.Integer(), nullable=True),
        sa.Column("deterministic_result_json", sa.JSON(), nullable=True),
        sa.Column("llm_result_json", sa.JSON(), nullable=True),
        sa.Column("grader_route", sa.Text(), nullable=True),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("hint_count", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assessment_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assessment_attempt_assessment_id"), ["assessment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assessment_attempt_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "chunk",
        sa.Column("document_version_id", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("t_start", sa.Float(), nullable=True),
        sa.Column("t_end", sa.Float(), nullable=True),
        sa.Column("skill_ids_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chunk", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chunk_document_version_id"), ["document_version_id"], unique=False
        )

    op.create_table(
        "experiment_arm",
        sa.Column("experiment_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("experiment_arm", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_experiment_arm_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "learning_event",
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("verb", sa.Text(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=False),
        sa.Column("object_id", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("activity_type", sa.Text(), nullable=False),
        sa.Column("representation", sa.Text(), nullable=True),
        sa.Column("modality", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("socratic", sa.Boolean(), nullable=False),
        sa.Column("experiment_arm", sa.Text(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("context_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("learning_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learning_event_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_event_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            "ix_learning_event_session_verb", ["session_id", "verb"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_learning_event_ts"), ["ts"], unique=False)
        batch_op.create_index(batch_op.f("ix_learning_event_verb"), ["verb"], unique=False)

    op.create_table(
        "model_call",
        sa.Column("learner_id", sa.Text(), nullable=True),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("registry_id", sa.Text(), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("route", sa.Text(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_call_learner_id"), ["learner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_model_call_registry_id"), ["registry_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_model_call_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_call_task"), ["task"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_call_ts"), ["ts"], unique=False)

    op.create_table(
        "parking_lot_item",
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("promoted_to", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["skill_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("parking_lot_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_parking_lot_item_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "retrieval_trace",
        sa.Column("learner_id", sa.Text(), nullable=True),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("collection", sa.Text(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("filters_json", sa.JSON(), nullable=False),
        sa.Column("bm25_scores_json", sa.JSON(), nullable=False),
        sa.Column("vector_scores_json", sa.JSON(), nullable=False),
        sa.Column("fused_json", sa.JSON(), nullable=False),
        sa.Column("reranked_json", sa.JSON(), nullable=True),
        sa.Column("chunk_ids_json", sa.JSON(), nullable=False),
        sa.Column("flagged_patterns_json", sa.JSON(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("retrieval_trace", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_retrieval_trace_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_retrieval_trace_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "review_item",
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("object_id", sa.Text(), nullable=True),
        sa.Column("item_type", sa.Text(), nullable=False),
        sa.Column("prompt_json", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["learning_object.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_item_learner_id"), ["learner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_item_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "session_checkpoint",
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("packet_json", sa.JSON(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_checkpoint", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_checkpoint_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_session_checkpoint_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "chunk_provenance",
        sa.Column("chunk_id", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("trust_tier", sa.Integer(), nullable=False),
        sa.Column("course", sa.Text(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("lecture", sa.Text(), nullable=True),
        sa.Column("ingested_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunk.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id"),
    )
    with op.batch_alter_table("chunk_provenance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chunk_provenance_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "competency_evidence",
        sa.Column("skill_id", sa.Text(), nullable=False),
        sa.Column("dimension", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("grader_level", sa.Text(), nullable=False),
        sa.Column("source_attempt_id", sa.Text(), nullable=True),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_attempt_id"],
            ["assessment_attempt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("competency_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competency_evidence_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competency_evidence_skill_id"), ["skill_id"], unique=False
        )

    op.create_table(
        "experiment_observation",
        sa.Column("experiment_id", sa.Text(), nullable=False),
        sa.Column("arm_id", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arm_id"],
            ["experiment_arm.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("experiment_observation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_experiment_observation_experiment_id"), ["experiment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_experiment_observation_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "memory_state",
        sa.Column("review_item_id", sa.Text(), nullable=False),
        sa.Column("fsrs_card_json", sa.JSON(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("due", sa.Text(), nullable=False),
        sa.Column("last_review", sa.Text(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_item_id"],
            ["review_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_item_id"),
    )
    with op.batch_alter_table("memory_state", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_state_due"), ["due"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_state_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "representation",
        sa.Column("object_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model_call_id", sa.Text(), nullable=True),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["model_call.id"],
        ),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["learning_object.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("representation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_representation_object_id"), ["object_id"], unique=False
        )

    op.create_table(
        "review_log",
        sa.Column("review_item_id", sa.Text(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("predicted_retrievability", sa.Float(), nullable=True),
        sa.Column("fsrs_log_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_item_id"],
            ["review_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_log_learner_id"), ["learner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_review_log_review_item_id"), ["review_item_id"], unique=False
        )

    op.create_table(
        "tutor_trace",
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("turn_id", sa.Text(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("sections_json", sa.JSON(), nullable=False),
        sa.Column("dropped_json", sa.JSON(), nullable=False),
        sa.Column("model_call_id", sa.Text(), nullable=True),
        sa.Column("retrieval_trace_id", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["model_call.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retrieval_trace_id"],
            ["retrieval_trace.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tutor_trace", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tutor_trace_learner_id"), ["learner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tutor_trace_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tutor_trace_turn_id"), ["turn_id"], unique=False)

    # ### end Alembic commands ###
    for ddl in LEARNING_EVENT_GUARDS.values():
        op.execute(ddl)


def downgrade() -> None:
    """Downgrade schema."""
    for name in LEARNING_EVENT_GUARDS:
        op.execute(drop_guard(name))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tutor_trace", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tutor_trace_turn_id"))
        batch_op.drop_index(batch_op.f("ix_tutor_trace_session_id"))
        batch_op.drop_index(batch_op.f("ix_tutor_trace_learner_id"))

    op.drop_table("tutor_trace")
    with op.batch_alter_table("review_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_log_review_item_id"))
        batch_op.drop_index(batch_op.f("ix_review_log_learner_id"))

    op.drop_table("review_log")
    with op.batch_alter_table("representation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_representation_object_id"))

    op.drop_table("representation")
    with op.batch_alter_table("memory_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_state_learner_id"))
        batch_op.drop_index(batch_op.f("ix_memory_state_due"))

    op.drop_table("memory_state")
    with op.batch_alter_table("experiment_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiment_observation_learner_id"))
        batch_op.drop_index(batch_op.f("ix_experiment_observation_experiment_id"))

    op.drop_table("experiment_observation")
    with op.batch_alter_table("competency_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competency_evidence_skill_id"))
        batch_op.drop_index(batch_op.f("ix_competency_evidence_learner_id"))

    op.drop_table("competency_evidence")
    with op.batch_alter_table("chunk_provenance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunk_provenance_source_id"))

    op.drop_table("chunk_provenance")
    with op.batch_alter_table("session_checkpoint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_checkpoint_session_id"))
        batch_op.drop_index(batch_op.f("ix_session_checkpoint_learner_id"))

    op.drop_table("session_checkpoint")
    with op.batch_alter_table("review_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_item_skill_id"))
        batch_op.drop_index(batch_op.f("ix_review_item_learner_id"))

    op.drop_table("review_item")
    with op.batch_alter_table("retrieval_trace", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_retrieval_trace_session_id"))
        batch_op.drop_index(batch_op.f("ix_retrieval_trace_learner_id"))

    op.drop_table("retrieval_trace")
    with op.batch_alter_table("parking_lot_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parking_lot_item_learner_id"))

    op.drop_table("parking_lot_item")
    with op.batch_alter_table("model_call", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_call_ts"))
        batch_op.drop_index(batch_op.f("ix_model_call_task"))
        batch_op.drop_index(batch_op.f("ix_model_call_session_id"))
        batch_op.drop_index(batch_op.f("ix_model_call_registry_id"))
        batch_op.drop_index(batch_op.f("ix_model_call_learner_id"))

    op.drop_table("model_call")
    with op.batch_alter_table("learning_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_event_verb"))
        batch_op.drop_index(batch_op.f("ix_learning_event_ts"))
        batch_op.drop_index("ix_learning_event_session_verb")
        batch_op.drop_index(batch_op.f("ix_learning_event_session_id"))
        batch_op.drop_index(batch_op.f("ix_learning_event_learner_id"))

    op.drop_table("learning_event")
    with op.batch_alter_table("experiment_arm", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiment_arm_experiment_id"))

    op.drop_table("experiment_arm")
    with op.batch_alter_table("chunk", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunk_document_version_id"))

    op.drop_table("chunk")
    with op.batch_alter_table("assessment_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assessment_attempt_learner_id"))
        batch_op.drop_index(batch_op.f("ix_assessment_attempt_assessment_id"))

    op.drop_table("assessment_attempt")
    with op.batch_alter_table("adaptation_decision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adaptation_decision_learner_id"))
        batch_op.drop_index(batch_op.f("ix_adaptation_decision_adaptation_id"))

    op.drop_table("adaptation_decision")
    with op.batch_alter_table("skill_edge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_edge_to_skill_id"))
        batch_op.drop_index(batch_op.f("ix_skill_edge_from_skill_id"))

    op.drop_table("skill_edge")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_learner_id"))

    op.drop_table("session")
    with op.batch_alter_table("learning_object", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_object_skill_id"))

    op.drop_table("learning_object")
    with op.batch_alter_table("learner_preference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learner_preference_learner_id"))

    op.drop_table("learner_preference")
    with op.batch_alter_table("experiment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiment_learner_id"))

    op.drop_table("experiment")
    with op.batch_alter_table("document_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_version_document_id"))
        batch_op.drop_index(batch_op.f("ix_document_version_content_hash"))

    op.drop_table("document_version")
    with op.batch_alter_table("competency_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competency_state_skill_id"))
        batch_op.drop_index(batch_op.f("ix_competency_state_learner_id"))

    op.drop_table("competency_state")
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assessment_skill_id"))

    op.drop_table("assessment")
    with op.batch_alter_table("adaptation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adaptation_learner_id"))

    op.drop_table("adaptation")
    with op.batch_alter_table("skill_node", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_node_domain"))

    op.drop_table("skill_node")
    op.drop_table("model_registry")
    op.drop_table("learner_profile")
    op.drop_table("index_state")
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_course"))

    op.drop_table("document")
    op.drop_table("assessment_rubric")
    # ### end Alembic commands ###
