"""saved tutor answers

Revision ID: 1c27f2b8243b
Revises: cde4fcb3e2c7
Create Date: 2026-10-01 18:11:38.000069

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c27f2b8243b"
down_revision: str | Sequence[str] | None = "cde4fcb3e2c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor_answer",
        sa.Column("turn_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("surface", sa.Text(), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learner_profile.id"], name="fk_tutor_answer_learner"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], name="fk_tutor_answer_session"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "turn_id", name="uq_tutor_answer_learner_turn"),
    )
    with op.batch_alter_table("tutor_answer", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tutor_answer_learner_id"), ["learner_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tutor_answer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tutor_answer_learner_id"))

    op.drop_table("tutor_answer")
    # ### end Alembic commands ###
