"""saved answer feedback

Revision ID: 1df12eb8e5ba
Revises: 58e8952b930d
Create Date: 2026-10-01 19:19:08.845674

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1df12eb8e5ba"
down_revision: str | Sequence[str] | None = "58e8952b930d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor_answer_feedback",
        sa.Column("answer_id", sa.Text(), nullable=False),
        sa.Column("verdict", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["tutor_answer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "answer_id", name="uq_answer_feedback_owner_answer"),
    )
    with op.batch_alter_table("tutor_answer_feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tutor_answer_feedback_answer_id"), ["answer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tutor_answer_feedback_learner_id"), ["learner_id"], unique=False
        )


def downgrade() -> None:
    op.drop_table("tutor_answer_feedback")
