"""p4 curriculum drafts, content reports, skill_node.course

Revision ID: 367349aa228b
Revises: ffb15bdebad6
Create Date: 2026-09-20 15:43:15.791904

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "367349aa228b"
down_revision: str | Sequence[str] | None = "ffb15bdebad6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_report",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("turn_id", sa.Text(), nullable=True),
        sa.Column("chunk_id", sa.Text(), nullable=True),
        sa.Column("skill_id", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learner_profile.id"], name="fk_content_report_learner"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_content_report"),
    )
    with op.batch_alter_table("content_report", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_content_report_chunk_id"), ["chunk_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_content_report_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_content_report_skill_id"), ["skill_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_content_report_turn_id"), ["turn_id"], unique=False)

    op.create_table(
        "curriculum_draft",
        sa.Column("course", sa.Text(), nullable=False),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("validation_json", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("published_at", sa.Text(), nullable=True),
        sa.Column("model_call_id", sa.Text(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learner_profile.id"], name="fk_curriculum_draft_learner"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_curriculum_draft"),
    )
    with op.batch_alter_table("curriculum_draft", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_curriculum_draft_course"), ["course"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_curriculum_draft_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_curriculum_draft_status"), ["status"], unique=False)

    with op.batch_alter_table("skill_node", schema=None) as batch_op:
        batch_op.add_column(sa.Column("course", sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f("ix_skill_node_course"), ["course"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skill_node", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_node_course"))
        batch_op.drop_column("course")

    with op.batch_alter_table("curriculum_draft", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_curriculum_draft_status"))
        batch_op.drop_index(batch_op.f("ix_curriculum_draft_learner_id"))
        batch_op.drop_index(batch_op.f("ix_curriculum_draft_course"))

    op.drop_table("curriculum_draft")
    with op.batch_alter_table("content_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_report_turn_id"))
        batch_op.drop_index(batch_op.f("ix_content_report_skill_id"))
        batch_op.drop_index(batch_op.f("ix_content_report_learner_id"))
        batch_op.drop_index(batch_op.f("ix_content_report_chunk_id"))

    op.drop_table("content_report")
    # ### end Alembic commands ###
