"""workspace request recovery

Revision ID: 55d7f6e0304b
Revises: c16887272890
Create Date: 2026-10-01 23:51:16.940608

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55d7f6e0304b"
down_revision: str | Sequence[str] | None = "c16887272890"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_request",
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("request_key", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "request_key", name="uq_workspace_request_owner_key"),
    )
    with op.batch_alter_table("workspace_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workspace_request_learner_id"), ["learner_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspace_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_request_learner_id"))

    op.drop_table("workspace_request")
    # ### end Alembic commands ###
