"""learner_question_state

Revision ID: 6b53cfd352a8
Revises: f628a4d31c90
Create Date: 2026-10-08 11:32:54.687678

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b53cfd352a8"
down_revision: str | Sequence[str] | None = "f628a4d31c90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_state",
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.Column("assessment_id", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('active', 'suspended', 'superseded', 'retired')",
            name="ck_question_state_state",
        ),
        sa.CheckConstraint("revision >= 1", name="ck_question_state_revision"),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("learner_id", "assessment_id"),
    )
    op.create_table(
        "question_transition",
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("assessment_id", sa.Text(), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("learner_id", "request_id"),
    )
    with op.batch_alter_table("question_transition", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_transition_assessment_id"), ["assessment_id"], unique=False
        )


def downgrade() -> None:
    op.drop_index("ix_question_transition_assessment_id", table_name="question_transition")
    op.drop_table("question_transition")
    op.drop_table("question_state")
