"""private_correction_drafts

Revision ID: 773f25ae3e92
Revises: 6b53cfd352a8
Create Date: 2026-10-08 15:13:07.661506

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "773f25ae3e92"
down_revision: str | Sequence[str] | None = "6b53cfd352a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_correction_draft",
        sa.Column("assessment_id", sa.Text(), nullable=False),
        sa.Column("feedback_id", sa.Text(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("original_json", sa.JSON(), nullable=False),
        sa.Column("original_fingerprint", sa.Text(), nullable=False),
        sa.Column("question_revision", sa.Integer(), nullable=False),
        sa.Column("candidate_json", sa.JSON(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.CheckConstraint("status IN ('draft', 'discarded')", name="ck_correction_draft_status"),
        sa.CheckConstraint("revision >= 1", name="ck_correction_draft_revision"),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["question_feedback.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_correction_draft", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_correction_draft_assessment_id"),
            ["assessment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_question_correction_draft_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "question_correction_command",
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("draft_id", sa.Text(), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["question_correction_draft.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("learner_id", "request_id"),
    )
    with op.batch_alter_table("question_correction_command", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_correction_command_draft_id"), ["draft_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_correction_command", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_correction_command_draft_id"))

    op.drop_table("question_correction_command")
    with op.batch_alter_table("question_correction_draft", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_correction_draft_learner_id"))
        batch_op.drop_index(batch_op.f("ix_question_correction_draft_assessment_id"))

    op.drop_table("question_correction_draft")
    # ### end Alembic commands ###
