"""private answer vector cache

Revision ID: c16887272890
Revises: 1df12eb8e5ba
Create Date: 2026-10-01 20:22:42.896808

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c16887272890"
down_revision: str | Sequence[str] | None = "1df12eb8e5ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor_answer_vector",
        sa.Column("answer_id", sa.Text(), nullable=False),
        sa.Column("answer_fingerprint", sa.Text(), nullable=False),
        sa.Column("model_key", sa.Text(), nullable=False),
        sa.Column("vector_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["answer_id"], ["tutor_answer.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "answer_id", name="uq_answer_vector_owner_answer"),
    )
    with op.batch_alter_table("tutor_answer_vector", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tutor_answer_vector_answer_id"), ["answer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tutor_answer_vector_learner_id"),
            ["learner_id"],
            unique=False,
        )


def downgrade() -> None:
    op.drop_table("tutor_answer_vector")
