"""knowledge areas and question feedback

Revision ID: cde4fcb3e2c7
Revises: d4a7b2c9e1f0
Create Date: 2026-09-24 10:15:19.468575

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cde4fcb3e2c7"
down_revision: str | Sequence[str] | None = "d4a7b2c9e1f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_area",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("terms_json", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "question_feedback",
        sa.Column("target_key", sa.Text(), nullable=False),
        sa.Column("draft_id", sa.Text(), nullable=True),
        sa.Column("assessment_id", sa.Text(), nullable=True),
        sa.Column("draft_version", sa.Integer(), nullable=True),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("labels_json", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("snapshot_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("withdrawn_at", sa.Text(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("learner_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["curriculum_draft.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_feedback_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_feedback_target_key"), ["target_key"], unique=False
        )

    with op.batch_alter_table("curriculum_draft", schema=None) as batch_op:
        batch_op.add_column(sa.Column("area_id", sa.Text(), nullable=True))
        batch_op.alter_column("course", existing_type=sa.TEXT(), nullable=True)
        batch_op.create_index(batch_op.f("ix_curriculum_draft_area_id"), ["area_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_curriculum_draft_area", "knowledge_area", ["area_id"], ["id"]
        )

    with op.batch_alter_table("skill_node", schema=None) as batch_op:
        batch_op.add_column(sa.Column("area_id", sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f("ix_skill_node_area_id"), ["area_id"], unique=False)
        batch_op.create_foreign_key("fk_skill_node_area", "knowledge_area", ["area_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Area drafts have no course. Preserve them under an explicit legacy label on downgrade.
    op.execute(
        "UPDATE curriculum_draft SET course = 'Knowledge area (legacy)' WHERE course IS NULL"
    )
    with op.batch_alter_table("skill_node", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("fk_skill_node_area", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_skill_node_area_id"))
        batch_op.drop_column("area_id")

    with op.batch_alter_table("curriculum_draft", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("fk_curriculum_draft_area", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_curriculum_draft_area_id"))
        batch_op.alter_column("course", existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column("area_id")

    with op.batch_alter_table("question_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_feedback_target_key"))
        batch_op.drop_index(batch_op.f("ix_question_feedback_learner_id"))

    op.drop_table("question_feedback")
    op.drop_table("knowledge_area")
    # ### end Alembic commands ###
