"""p7 content_report assessment_id

Revision ID: e3ee9810831b
Revises: ac95f48189c0
Create Date: 2026-09-20 22:33:48.963194

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3ee9810831b"
down_revision: str | Sequence[str] | None = "ac95f48189c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("content_report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("assessment_id", sa.Text(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_content_report_assessment_id"), ["assessment_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("content_report", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_report_assessment_id"))
        batch_op.drop_column("assessment_id")

    # ### end Alembic commands ###
