#!/usr/bin/env python3
"""Stage 2 benchmark (docs/ROADMAP.md). Run: make bench s=2
A planner produces valid plans for all mode × energy combos (× due / no due)
B representation switch keeps object identity (two kinds rendered by the real model on data/bench2.db;
  the same object_id; a repeat request is served from cache with the same representation id)
C resume from a checkpoint mid-session (turn → UI checkpoint phase=assess → reload → same skill/phase/hint)
D a challenge round trip: planted error generated by the model, graded against the hidden key, delayed item
"""

import asyncio
import json
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from sqlalchemy import select  # noqa: E402

from app.db import models  # noqa: E402
from app.evals.harness import open_world, results_dir  # noqa: E402
from app.kernel import planner, skill_graph  # noqa: E402
from app.kernel import session as ksession  # noqa: E402
from app.orchestrator import challenge  # noqa: E402
from app.orchestrator import representations as orep  # noqa: E402
from app.orchestrator.grader import Grader  # noqa: E402
from app.orchestrator.tutor import TutorTurn  # noqa: E402
from app.schemas.common import Mode  # noqa: E402
from app.schemas.grading import AttemptRequest  # noqa: E402
from app.schemas.tutor import TurnRequest  # noqa: E402

results: dict[str, dict[str, Any]] = {}


def record(key: str, status: str, **data: Any) -> None:
    results[key] = {"status": status, **data}
    print(f"[{status:4}] {key}: {json.dumps(data, default=str)[:600]}", flush=True)


def check_a() -> None:
    combos = 0
    for mode in ("novelty", "steady", "low_capacity"):
        for energy in range(1, 6):
            for due in (0, 6):
                for prefs in ({}, {"planner.movement": "after"}, {"planner.challenge": False}):
                    p = planner.plan_session(
                        planner.PlanInput(
                            mode=mode,
                            energy=energy,
                            due_reviews=due,
                            next_skill_id="k",
                            next_skill_mastery=0.4,
                            review_node_ids=["a"] if due else [],
                            preferences=prefs,
                        )
                    )
                    planner.validate_plan(p)
                    combos += 1
    record("A planner valid for all mode x energy", "PASS", combos=combos)


async def check_b(world: Any) -> None:
    async with world.session_factory() as db:
        s = await ksession.start(db, world.learner_id, mode=Mode.STEADY, energy=3)
        node = await skill_graph.next_skill(db, world.learner_id)
        assert node
        gw = world.gateway(db)
        a = await orep.render(db, gw, world.repo, s, node, "analogy")
        b = await orep.render(db, gw, world.repo, s, node, "derivation")
        again = await orep.render(db, gw, world.repo, s, node, "analogy")
        ok = (
            a["object_id"] == b["object_id"]
            and not a["cached"]
            and not b["cached"]
            and again["cached"]
            and again["representation_id"] == a["representation_id"]
        )
        calls = len(
            (
                await db.execute(
                    select(models.ModelCall).where(
                        models.ModelCall.metadata_json["representation"]
                        .as_string()
                        .in_(["analogy", "derivation"])
                    )
                )
            )
            .scalars()
            .all()
        )
        record(
            "B representation switch keeps object identity",
            "PASS" if ok else "FAIL",
            object_id=a["object_id"],
            kinds=[a["kind"], b["kind"]],
            cached_on_repeat=again["cached"],
            model_calls=calls,
            analogy=a["content"][:160],
            derivation=b["content"][:160],
        )
        await ksession.end(db, s.id, energy_after=3, self_report=3)


async def check_c(world: Any) -> None:
    async with world.session_factory() as db:
        s = await ksession.start(db, world.learner_id, mode=Mode.STEADY, energy=3)
        turn = TutorTurn(db, world.gateway(db), world.repo)
        meta = None
        async for kind, data in turn.run(
            TurnRequest(session_id=s.id, text="I'm stuck", action="hint")
        ):
            if kind == "meta":
                meta = data
        assert meta
        cp = await ksession.load_checkpoint(db, s.id) or {}
        await ksession.save_checkpoint(db, s, {**cp, "phase": "assess", "block_index": 2})
    # "reload": a fresh DB session
    async with world.session_factory() as db:
        s2 = await ksession.get(db, s.id)
        cp2 = await ksession.load_checkpoint(db, s2.id) or {}
        ok = (
            cp2.get("skill_id") == meta["skill_id"]
            and cp2.get("phase") == "assess"
            and cp2.get("hint_level") == 1
            and cp2.get("block_index") == 2
            and s2.ended_at is None
        )
        record(
            "C resume from checkpoint mid-session",
            "PASS" if ok else "FAIL",
            checkpoint={
                k: cp2.get(k) for k in ("skill_id", "phase", "hint_level", "block_index", "action")
            },
        )
        await ksession.end(db, s2.id, energy_after=3, self_report=3)


async def check_d(world: Any) -> None:
    async with world.session_factory() as db:
        s = await ksession.start(db, world.learner_id, mode=Mode.NOVELTY, energy=4)
        node = await skill_graph.get_node_by_slug(db, "attn-scaled")
        assert node
        gw = world.gateway(db)
        view = await challenge.start(db, gw, world.repo, s, node, "planted_error")
        now = datetime.now(UTC)
        res = await Grader(db, gw).grade(
            AttemptRequest(
                session_id=s.id,
                assessment_id=view.assessment_id,
                answer=(
                    "The error: it should divide by the square root of d_k, not d_k itself, "
                    "because the dot product variance is d_k so sqrt restores unit variance."
                ),
                confidence_pre=4,
            ),
            now=now,
        )
        delayed = datetime.fromisoformat(str(res.review["due"])) >= now + timedelta(
            days=2
        ) - timedelta(minutes=1)
        ok = res.dimension == "application" and res.grader_level in ("local", "hosted") and delayed
        record(
            "D challenge round trip",
            "PASS" if ok else "FAIL",
            prompt=view.prompt[:200],
            criteria=view.criteria,
            score=res.score,
            grader=res.grader_level,
            due=res.review["due"],
            feedback=res.feedback[:160],
        )
        await ksession.end(db, s.id, energy_after=3, self_report=3)


async def main() -> int:
    check_a()
    world = await open_world("bench2.db", fresh=True)
    try:
        for name, fn in (("B", check_b), ("C", check_c), ("D", check_d)):
            try:
                await fn(world)
            except Exception as e:
                record(f"{name} (crashed)", "FAIL", error=f"{type(e).__name__}: {e}")
    finally:
        await world.close()
    out = results_dir() / "bench_stage2.json"
    out.write_text(json.dumps(results, indent=2, default=str))
    failed = [k for k, v in results.items() if v["status"] == "FAIL"]
    print(
        "\nSTAGE 2 BENCHMARK:",
        "FAIL" if failed else "PASS",
        f"({len(results)} checks, {len(failed)} failed)",
    )
    print(f"written: {out}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
