from fastapi import APIRouter

from app.api import (
    adaptations,
    areas,
    assess,
    challenge,
    corpus,
    curriculum,
    exercises,
    experiments,
    health,
    learner,
    listening,
    models_admin,
    parking,
    plan,
    playground,
    practice,
    preferences,
    representations,
    review,
    sessions,
    skills,
    tutor,
    voice,
)

api_router = APIRouter(prefix="/api")
for r in (
    health,
    learner,
    skills,
    sessions,
    plan,
    playground,
    preferences,
    representations,
    challenge,
    tutor,
    assess,
    review,
    parking,
    corpus,
    areas,
    adaptations,
    models_admin,
    listening,
    exercises,
    voice,
    experiments,
    practice,
    curriculum,
):
    api_router.include_router(r.router)
