import { expect, test } from '@playwright/test'
import { API, endOpenSession, expectOk } from './helpers'

for (const width of [320, 390, 1280]) test(`lesson leads before optional tools ${width}`, async ({ page, request }, info) => {
  await endOpenSession(request)
  try {
    for (const key of ['goal.area', 'goal.course'])
      await request.put(`${API}/api/preferences`, { data: { key, value: '' } })
    const response = await request.post(`${API}/api/sessions`, { data: { mode: 'steady', energy: 3 } })
    await expectOk(response)
    const session = await response.json()
    const index = session.plan.findIndex((block: { type: string }) => block.type === 'new_material')
    await expectOk(await request.post(`${API}/api/plan/blocks/start`, { data: { session_id: session.id, index } }))
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    const explanation = page.getByRole('heading', { name: 'Your explanation' })
    await expect(explanation).toBeVisible()
    await page.screenshot({ path: info.outputPath('lesson.png'), fullPage: true })
    const start = page.getByRole('button', { name: 'Start explanation', exact: true })
    const tools = page.locator('summary').filter({ hasText: /^Work alongside$/ })
    const startBox = await start.boundingBox()
    const toolsBox = await tools.boundingBox()
    console.log(JSON.stringify({ width, startTop: startBox?.y, toolsTop: toolsBox?.y }))
    expect(startBox!.y).toBeLessThan(toolsBox!.y)
    await start.focus()
    await page.keyboard.press('Tab')
    await expect(page.locator('summary').filter({ hasText: /^More ways to learn$/ })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(page.getByLabel('Ask about this lesson (optional)')).toBeFocused()
    await tools.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByText('Keep this lesson open with a quiet work panel.', { exact: false })).toBeVisible()
    await tools.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('link', { name: 'Open lesson experiment' })).not.toBeVisible()
    const code = page.locator('summary').filter({ hasText: /^Try a coding experiment$/ })
    await code.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('link', { name: 'Open lesson experiment' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Pause and return Home' }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('button', { name: 'Continue', exact: true })).toBeVisible()
  } finally { await endOpenSession(request) }
})
