import { expect, test } from '@playwright/test'
// Keep default journeys independent of the owner's local guide. Specific tests override this.
test.beforeEach(async ({ page }) => {
  await page.route('**/local-learning/program.json', route => route.fulfill({ status: 404, json: {} }))
})
for (const width of [390, 1280]) test(`material search keeps independent results and query ${width}`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 })
  let sourceFail = true
  const requests: string[] = []
  await page.route('**/api/answers?*', route => { requests.push('answers'); return route.fulfill({ json: { items: [{ id: 'one', request_text: 'Explain groups', preview: 'Compare groups.', created_at: '2026-10-01', surface: 'tutor' }], next_cursor: null } }) })
  await page.route('**/api/corpus/search', route => { requests.push('sources'); return sourceFail ? route.fulfill({ status: 503, json: {} }) : route.fulfill({ json: { hits: [{ chunk_id: 'passage', citation: 'Example passage', source_type: 'text', text: 'Inspect the evidence.', flagged: ['warning'], quarantined: true }] } }) })
  await page.route('**/api/curriculum/chunks/passage', route => route.fulfill({ json: { chunk_id: 'passage', citation: 'Example passage', text: 'Full original evidence.', document_title: 'Example', source_type: 'text', trust_tier: 2, uri: 'example.txt', open_url: null } }))
  await page.goto('/search')
  expect(requests).toEqual([])
  await page.getByRole('searchbox', { name: 'Search phrase' }).fill('groups')
  expect(requests).toEqual([])
  await page.getByRole('searchbox', { name: 'Search phrase' }).press('Enter')
  await expect(page).toHaveURL(/q=groups$/)
  await expect(page.getByRole('link', { name: 'Explain groups' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retry source search' })).toBeVisible()
  const answerCount = requests.filter(r => r === 'answers').length
  sourceFail = false
  await page.getByRole('button', { name: 'Retry source search' }).click()
  await expect(page.getByRole('link', { name: 'Example passage' })).toBeVisible()
  expect(requests.filter(r => r === 'answers')).toHaveLength(answerCount)
  await expect(page.getByText('Withheld from tutor context.')).toBeVisible()
  await page.screenshot({ path: info.outputPath('material-search.png'), fullPage: true })
  await page.getByRole('link', { name: 'Example passage' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByText('Full original evidence.')).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('searchbox', { name: 'Search phrase' })).toHaveValue('groups')
  await page.reload()
  await expect(page.getByRole('link', { name: 'Explain groups' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear search' }).click()
  await expect(page.getByText('Enter a phrase to search your local material.')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('old searches cannot replace a new query and invalid queries send nothing', async ({ page }) => {
  let release!: () => void
  const held = new Promise<void>(resolve => { release = resolve })
  const seen: string[] = []
  await page.route('**/api/answers?*', async route => {
    const q = new URL(route.request().url()).searchParams.get('q')!
    seen.push(q)
    if (q === 'old') await held
    await route.fulfill({ json: { items: [{ id: q, request_text: `Answer ${q}`, preview: q }], next_cursor: null } }).catch(() => {})
  })
  await page.route('**/api/corpus/search', route => route.fulfill({ json: { hits: [] } }))
  await page.goto(`/search?q=${'x'.repeat(201)}`)
  await expect(page.getByRole('alert')).toHaveText('Use a search of 200 characters or fewer.')
  expect(seen).toEqual([])
  await page.goto('/search?q=old')
  await expect(page.getByText('Searching saved explanations…')).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search phrase' }).fill('new')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Answer new' })).toBeVisible()
  release()
  await expect(page.getByRole('link', { name: 'Answer old' })).toHaveCount(0)
})

for (const width of [390, 1280]) test(`header search is reachable by keyboard and preserves return ${width}`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 })
  const writes: string[] = []
  page.on('request', request => {
    if (request.url().includes('/api/') && !['GET', 'OPTIONS'].includes(request.method())) writes.push(request.url())
  })
  await page.goto('/map')
  const entry = page.locator('header').getByRole('button', { name: 'Search or go to', exact: true })
  await expect(entry).toBeVisible()
  // Reach the persistent entry through the actual tab order, without opening navigation.
  await page.keyboard.press('Tab')
  for (let i = 0; i < 12 && !(await entry.evaluate(el => el === document.activeElement)); i++) await page.keyboard.press('Tab')
  await expect(entry).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog', { name: 'Search or go to' })).toBeVisible()
  await page.getByRole('button', { name: 'Open material search' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'Search material' })).toBeVisible()
  await expect(page.locator('#main-content')).toBeFocused()
  await page.screenshot({ path: info.outputPath('header-search.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.goBack()
  await expect(page).toHaveURL(/\/map$/)
  await expect(entry).toBeVisible()
  expect(writes).toEqual([])
})

for (const width of [390, 1280]) test(`quick navigation preserves work on cancel and filters locally ${width}`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/search')
  const original = page.getByRole('searchbox', { name: 'Search phrase', exact: true })
  await original.fill('unfinished thought')
  await original.press('Control+k')
  const menu = page.getByRole('dialog', { name: 'Search or go to' })
  await expect(menu).not.toBeVisible()
  const trigger = page.locator('header').getByRole('button', { name: 'Search or go to' })
  await trigger.focus()
  await page.keyboard.press('Control+k')
  await expect(menu).toBeVisible()
  const filter = menu.getByRole('searchbox')
  await expect(filter).toBeFocused()
  await filter.fill('skill')
  await expect(menu.getByRole('link', { name: 'Skill map', exact: true })).toBeVisible()
  await expect(menu.getByRole('link', { name: 'Models', exact: true })).toHaveCount(0)
  await page.screenshot({ path: info.outputPath('quick-navigation.png'), fullPage: true })
  expect(await menu.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(original).toHaveValue('unfinished thought')
  await trigger.click()
  await expect(filter).toHaveValue('')
  await filter.fill('zz-no-page')
  await expect(menu.getByRole('status')).toContainText('No page names match')
  await filter.fill('groups')
  await page.route('**/api/answers?*', route => route.fulfill({ json: { items: [], next_cursor: null } }))
  await page.route('**/api/corpus/search', route => route.fulfill({ json: { hits: [] } }))
  await filter.press('Enter')
  await expect(page).toHaveURL(/\/search\?q=groups$/)
  await expect(menu).not.toBeVisible()
  await expect(page.locator('#main-content')).toBeFocused()
})

test('area matches survive unavailable retrieval and browse without session writes', async ({ page }) => {
  const writes: string[] = []
  page.on('request', request => { if (request.url().includes('/api/') && request.method() !== 'GET' && !request.url().endsWith('/api/corpus/search')) writes.push(request.url()) })
  await page.route('**/api/areas', route => route.fulfill({ json: { areas: [{ id: 'area-python', title: 'Programming', description: 'Practice with Python.', terms: ['python'], slug: 'programming', documents: 0, courses: [], draft_ids: [], active_lessons: 0, related: [] }], unassigned_documents: 0, total_documents: 0 } }))
  await page.route('**/api/answers?*', route => route.fulfill({ json: { items: [], next_cursor: null } }))
  await page.route('**/api/corpus/search', route => route.fulfill({ status: 503, json: {} }))
  await page.goto('/search?q=PYTHON')
  const group = page.getByRole('region', { name: 'Knowledge areas', exact: true })
  const match = group.getByRole('link', { name: 'Programming', exact: true })
  await expect(match).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retry source search' })).toBeVisible()
  await match.focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/areas\?area=area-python$/)
  expect(writes).toEqual([])
})

test('project search validates local guide and opens the exact section', async ({ page }) => {
  let invalid = true
  const section = { id: 'clean', title: 'Cleaning', explanation: 'Compare representation before removing rows.', task: 'Compare groups', question: 'Why?', hint: 'Inspect groups', criteria: 'Explain selection', source: 'Local guide' }
  await page.route('**/local-learning/program.json', route => route.fulfill({ json: invalid ? { courses: 'invalid' } : { title: 'Study', courses: [{ id: 'data', title: 'Data practice', project: 'Compare groups', status: 'ready', sections: [section] }] } }))
  await page.route('**/api/answers?*', route => route.fulfill({ json: { items: [], next_cursor: null } }))
  await page.route('**/api/corpus/search', route => route.fulfill({ json: { hits: [] } }))
  await page.goto('/search?q=representation')
  await expect(page.getByRole('button', { name: 'Retry project search' })).toBeVisible()
  await expect(page.getByText('No saved explanations matched.')).toBeVisible()
  invalid = false
  await page.getByRole('button', { name: 'Retry project search' }).click()
  const link = page.getByRole('link', { name: 'Data practice · Cleaning' })
  await expect(link).toHaveAttribute('href', '/programs?course=data&step=clean')
  await link.focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/programs\?course=data&step=clean$/)
  await expect(page.getByRole('heading', { name: 'Cleaning', exact: true })).toBeVisible()
})
