import { expect, test } from '@playwright/test'

test('mobile menu closes safely and resize preserves visible keyboard focus', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/curriculum')
  const menu = page.getByRole('button', { name: /^Menu ·/ })
  const nav = page.getByRole('navigation', { name: 'Main navigation' })
  await expect(nav).toBeHidden()
  await menu.focus()
  await page.keyboard.press('Enter')
  await expect(nav).toBeVisible()
  await page.getByRole('link', { name: 'Home', exact: true }).focus()
  await page.keyboard.press('Escape')
  await expect(nav).toBeHidden()
  await expect(menu).toBeFocused()
  await page.setViewportSize({ width: 1280, height: 900 })
  await expect(nav).toBeVisible()
  await expect(nav.getByRole('link', { name: 'Home', exact: true })).toBeFocused()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(menu).toBeFocused()
  await menu.click()
  await nav.getByRole('link', { name: 'Projects', exact: true }).click()
  await expect(nav).toBeHidden()
  await expect(page.getByRole('main')).toBeFocused()
  await page.goBack()
  await expect(nav).toBeHidden()
  await expect(menu).toHaveText('Menu · Lesson drafts')
  await page.screenshot({ path: info.outputPath('mobile-menu-closed.png'), fullPage: true })
})
