import { test, expect } from '@playwright/test'
for (const width of [390, 1280]) test(`saved audio lesson return stays silent ${width}`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 })
  await page.addInitScript(() => {
    const Original = window.AudioContext
    Object.assign(window, { audioStarts: 0 })
    window.AudioContext = new Proxy(Original, { construct(target, args) { (window as unknown as { audioStarts: number }).audioStarts++; return Reflect.construct(target, args) } })
  })
  await page.goto('/playground/visualizer')
  await page.getByRole('button', { name: 'Learn', exact: true }).click()
  await page.getByRole('combobox', { name: 'Learning step', exact: true }).selectOption('2')
  await page.getByRole('button', { name: 'Save for later', exact: true }).click()
  await page.getByLabel('Thought to save').fill(`Remember harmonics ${width}`)
  await page.getByRole('button', { name: 'Save thought', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Learning step', exact: true }).selectOption('0')
  await page.goto('/')
  await page.getByRole('button', { name: 'Save for later', exact: true }).click()
  await page.getByText('Saved thoughts', { exact: true }).click()
  await page.getByRole('listitem').filter({ hasText: `Remember harmonics ${width}` }).getByRole('link').click()
  await expect(page.getByRole('combobox', { name: 'Learning step', exact: true })).toHaveValue('0')
  const open = page.getByRole('button', { name: 'Open saved audio lesson', exact: true })
  await open.focus(); await page.keyboard.press('Enter')
  await expect(page.getByRole('combobox', { name: 'Learning step', exact: true })).toHaveValue('2')
  expect(await page.evaluate(() => (window as unknown as { audioStarts: number }).audioStarts)).toBe(0)
  await page.screenshot({ path: info.outputPath('saved-audio-lesson.png'), fullPage: true })
  await page.goto('/playground/visualizer?saved_lesson=missing')
  await expect(page.getByText(/This saved audio lesson is unavailable/)).toBeVisible()
  expect(await page.evaluate(() => (window as unknown as { audioStarts: number }).audioStarts)).toBe(0)
})
