import { expect, test } from '@playwright/test'

for (const width of [390, 1280]) test(`saved thought reopens its task notebook after returning to the guide ${width}`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 })
  await page.route('**/local-learning/program.json', route => route.fulfill({ json: {
    title: 'Practice', courses: [{ id: 'fixture', title: 'Data practice', project: 'Count', status: 'Fixture', sections: [{ id: 'data', title: 'Inspect rows', explanation: 'Inspect first.', task: 'Count rows.', question: 'Why?', hint: 'Count.', criteria: 'Explain.', source: 'Fixture', practice: { notebook: '/local-learning/task.ipynb' } }] }],
  } }))
  await page.route('**/local-learning/task.ipynb', route => route.fulfill({ json: { nbformat: 4, metadata: { practice_checks: [{ name: 'Count', criterion: 'Two', code: 'assert 2 == 2' }] }, cells: [{ cell_type: 'code', source: 'print(2)' }] } }))
  await page.goto('/programs?course=fixture&step=data')
  await page.getByRole('button', { name: 'Try', exact: true }).click()
  await page.getByLabel('Project notes').fill('Retain my observation')
  await page.getByRole('button', { name: 'Open task starter notebook' }).click()
  await expect(page.getByRole('region', { name: 'Notebook workspace', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Use plain editor', exact: true }).click()
  await page.getByLabel('Starter code — edit your working copy').fill('print(42)')
  await page.getByRole('button', { name: 'Save for later', exact: true }).click()
  await page.getByLabel('Thought to save').fill(`Return to this starter ${width}`)
  await page.getByRole('button', { name: 'Save thought', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Back to task without results' }).click()
  await expect(page.getByLabel('Project notes')).toHaveValue('Retain my observation')
  await page.goto('/')
  await page.getByRole('button', { name: 'Save for later', exact: true }).click()
  await page.getByText('Saved thoughts', { exact: true }).click()
  await page.getByRole('listitem').filter({ hasText: `Return to this starter ${width}` }).getByRole('link').focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('region', { name: 'Notebook workspace', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Use plain editor', exact: true }).click()
  await expect(page.getByLabel('Starter code — edit your working copy')).toHaveValue('print(42)')
  await page.screenshot({ path: info.outputPath('returned-notebook.png'), fullPage: true })
  await page.getByRole('button', { name: 'Back to task without results' }).click()
  await expect(page.getByLabel('Project notes')).toHaveValue('Retain my observation')
  await page.goto('/programs?course=fixture&step=missing&view=task')
  await page.getByRole('button', { name: 'Save for later', exact: true }).click()
  await page.getByLabel('Thought to save').fill('Do not invent a missing step')
  await expect(page.getByText('No exact material link is attached to this thought.')).toBeVisible()
})
