import { expect, test } from '@playwright/test'
for (const width of [390, 1280]) {
  test(`lesson controls survive navigation and reload ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/playground/visualizer')
    await page.getByRole('button', { name: 'Learn', exact: true }).click()
    const step = page.getByRole('combobox', { name: 'Learning step' })
    await step.selectOption('2')
    await page.getByRole('combobox', { name: 'Test waveform' }).selectOption('square')
    await page.getByRole('slider', { name: 'Test amplitude' }).fill('0.4')
    await page.getByRole('button', { name: 'One hint', exact: true }).click()
    await page.getByRole('link', { name: 'Coding playground', exact: false }).click()
    await page.getByRole('link', { name: 'Open audio visualizer lab' }).click()
    await expect(step).toHaveValue('2')
    await page.reload()
    await expect(step).toHaveValue('2')
    await expect(page.getByRole('combobox', { name: 'Test waveform' })).toHaveValue('square')
    await expect(page.getByRole('slider', { name: 'Test amplitude' })).toHaveValue('0.4')
    await expect(page.getByRole('button', { name: 'Hide hint', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Start test signal', exact: true })).toBeEnabled()
    await expect(page.getByRole('button', { name: 'Pause demo', exact: true })).toBeDisabled()
    await page.getByRole('slider', { name: 'Test amplitude' }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(page.getByRole('slider', { name: 'Test amplitude' })).toHaveValue('0.39')
    await page.getByRole('heading', { name: 'Harmonics', exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: info.outputPath('lesson.png') })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}
