import { expect, test } from '@playwright/test'
for (const width of [390, 1280]) {
  test(`file returns paused after leaving the audio lab ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/playground/visualizer')
    await page.getByRole('button', { name: 'Open audio', exact: true }).click()
  const wav = Buffer.alloc(44 + 16000 * 2 * 10)
  wav.write('RIFF', 0)
  wav.writeUInt32LE(wav.length - 8, 4)
  wav.write('WAVEfmt ', 8)
  wav.writeUInt32LE(16, 16)
  wav.writeUInt16LE(1, 20)
  wav.writeUInt16LE(1, 22)
  wav.writeUInt32LE(16000, 24)
  wav.writeUInt32LE(32000, 28)
  wav.writeUInt16LE(2, 32)
  wav.writeUInt16LE(16, 34)
  wav.write('data', 36)
  wav.writeUInt32LE(wav.length - 44, 40)
  for (let i = 0; i < 160000; i++)
    wav.writeInt16LE(Math.round(4000 * Math.sin((2 * Math.PI * 440 * i) / 16000)), 44 + i * 2)

    await page.getByLabel('Audio file', { exact: true }).setInputFiles({ name: 'test.wav', mimeType: 'audio/wav', buffer: wav })
    await page.getByRole('button', { name: 'Play file silently' }).click()
    const timeline = page.getByRole('slider', { name: /^Playback timeline/ })
    await expect(timeline).toBeEnabled()
    await page.getByRole('button', { name: 'Pause file', exact: true }).click()
    await timeline.fill('4')
    await page.getByRole('link', { name: 'Coding playground', exact: false }).click()
    await page.getByRole('link', { name: 'Open audio visualizer lab' }).click()
    await expect(timeline).toHaveValue('4')
    await expect(timeline).toBeDisabled()
    await expect(page.getByRole('checkbox', { name: 'Hear audio at half volume' })).not.toBeChecked()
    await expect(page.getByRole('button', { name: 'Capture current picture', exact: true })).toBeDisabled()
    await page.screenshot({ path: info.outputPath('paused-recovery.png'), fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const resume = page.getByRole('button', { name: 'Resume file', exact: true })
    await resume.focus()
    await page.keyboard.press('Enter')
    await expect.poll(async () => Number(await timeline.inputValue())).toBeGreaterThan(4)
    await page.reload()
    await expect(page.getByRole('button', { name: 'Start demo', exact: true })).toBeEnabled()
    await expect(page.getByText('Selected: test.wav', { exact: true })).toHaveCount(0)
  })
}
