import { expect, test } from '@playwright/test'
for (const width of [390, 1280]) {
  test(`comparison survives step switch and reload ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/playground/visualizer')
    await page.getByRole('button', { name: 'Learn', exact: true }).click()
    const step = page.getByRole('combobox', { name: 'Learning step' })
    await step.selectOption('4')
    await page.getByRole('button', { name: 'Choose a frequency region', exact: true }).click()
    const prediction = page.getByRole('combobox', { name: 'Optional prediction: what will happen to size?' })
    await prediction.selectOption('Smaller')
    await page.getByRole('button', { name: 'Show experiment hint', exact: true }).click()
    await page.getByRole('button', { name: 'Try change and compare', exact: true }).click()
    await step.selectOption('0')
    await step.selectOption('4')
    await expect(prediction).toHaveValue('Smaller')
    await page.getByRole('link', { name: 'Coding playground', exact: false }).click()
    await page.getByRole('link', { name: 'Open audio visualizer lab' }).click()
    await page.reload()
    await expect(prediction).toHaveValue('Smaller')
    await expect(page.getByRole('button', { name: 'Hide experiment hint', exact: true })).toBeVisible()
    await expect(page.getByRole('status').filter({ hasText: 'Comparison ready' })).toBeVisible()
    await page.getByRole('region', { name: 'Guided comparison' }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: info.outputPath('comparison.png') })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const restart = page.getByRole('button', { name: 'Restart experiment', exact: true })
    await restart.focus()
    await page.keyboard.press('Enter')
    await expect(prediction).toHaveValue('')
    await expect(page.getByRole('status').filter({ hasText: 'Comparison ready' })).toHaveCount(0)
  })
}
