/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness + DB connectivity */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/learner/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The owner profile (single learner in Phase 1) */
    get: operations['me_api_learner_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/skills': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Skill map with mastery + unlock state (open learner model) */
    get: operations['list_skills_api_skills_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/skills/map': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Whole skill map with competency + memory overlays and a Mermaid rendering */
    get: operations['skill_map_api_skills_map_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/skills/{skill_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** One skill with its state */
    get: operations['get_skill_api_skills__skill_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start a session (learner-chosen mode + energy) */
    post: operations['start_api_sessions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/sessions/current': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The latest session that has not ended (for resume after reload) */
    get: operations['current_api_sessions_current_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/sessions/{session_id}/checkpoint': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Merge UI state (phase, skill, block) into the resume checkpoint */
    post: operations['checkpoint_api_sessions__session_id__checkpoint_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/sessions/{session_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Session state */
    get: operations['get_api_sessions__session_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/sessions/{session_id}/end': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** End with confidence-rated recap */
    post: operations['end_api_sessions__session_id__end_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/plan/preview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Plan for a mode/energy before starting a session */
    get: operations['preview_api_plan_preview_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/plan/blocks/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start a planned block (emits block_started) */
    post: operations['start_block_api_plan_blocks_start_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/plan/blocks/end': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** End a block; early switches out of new material need a grasp check */
    post: operations['end_block_api_plan_blocks_end_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/plan/replan': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Energy check-in mid-session: records the new energy and proposes a re-scaled plan */
    post: operations['replan_api_plan_replan_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/preferences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** All structured preferences with their specs (defaults filled in) */
    get: operations['get_all_api_preferences_get']
    /** Set one preference (explicit by default; adaptations log an adapted event) */
    put: operations['set_one_api_preferences_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/preferences/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Reset one preference to its default */
    delete: operations['reset_api_preferences__key__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/objects/{skill_id}/representations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Representation kinds for a skill's LearningObject (cached/allowed flags) */
    get: operations['kinds_api_objects__skill_id__representations_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/objects/{skill_id}/representations/prefer': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Record which of two representations worked better (preferred event) */
    post: operations['prefer_api_objects__skill_id__representations_prefer_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/objects/{skill_id}/representations/{kind}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Show it differently: render (or fetch cached) one representation */
    post: operations['render_api_objects__skill_id__representations__kind__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenge/modes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Available critical-thinking challenge modes (opt-in) */
    get: operations['modes_api_challenge_modes_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenge/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Generate (or reuse) a challenge item for the current skill */
    post: operations['start_api_challenge_start_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenge/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit a challenge answer (graded against the hidden key; schedules a delayed item) */
    post: operations['submit_api_challenge_submit_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tutor/stream': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** One tutor turn as SSE (meta, token*, done | error) */
    post: operations['stream_api_tutor_stream_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tutor/turn': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** One tutor turn, buffered (tests, scripts, benchmarks) */
    post: operations['turn_api_tutor_turn_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/assess/next': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Next assessment item for a skill (mcq → cloze → explain-back rotation) */
    get: operations['next_item_api_assess_next_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/assess/attempt': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit an answer with a prior confidence rating; graded hierarchically */
    post: operations['attempt_api_assess_attempt_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/review/due': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Due review items, capped to the minimum-viable review for this session */
    get: operations['due_api_review_due_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/review/{item_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Rate a recalled item 1-4 (FSRS) */
    post: operations['rate_api_review__item_id__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/parking': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Parked items */
    get: operations['list_parked_api_parking_get']
    put?: never
    /** Park a tangent (≤ 2 interactions, linked to the current node) */
    post: operations['park_api_parking_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/parking/{item_id}/promote': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Promote a parked tangent: to the next session (Home reminder) or onto a skill node */
    post: operations['promote_api_parking__item_id__promote_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/parking/{item_id}/drop': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Drop a parked or promoted item */
    post: operations['drop_api_parking__item_id__drop_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/corpus/stats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Corpus overview: courses, chunks, flags, index state */
    get: operations['stats_api_corpus_stats_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/corpus/documents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Documents (latest version each), optionally by course */
    get: operations['documents_api_corpus_documents_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/corpus/ingest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Ingest a local file or course folder (idempotent by content hash) */
    post: operations['ingest_api_corpus_ingest_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/corpus/documents/{document_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove a document (all versions) from SQLite and the index */
    delete: operations['forget_api_corpus_documents__document_id__delete']
    options?: never
    head?: never
    /** Re-decide a document's trust tier (provenance + index payload; no re-ingest) */
    patch: operations['retier_api_corpus_documents__document_id__patch']
    trace?: never
  }
  '/api/corpus/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Inspect hybrid retrieval: fused, dense, sparse and rerank scores
     * @description With `tutor_view`, the tutor's trust floor applies and hits the tutor would quarantine are
     *     marked (kept visible, so the owner can see what was withheld).
     */
    post: operations['search_api_corpus_search_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Open proposal cards */
    get: operations['pending_api_adaptations_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations/observe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Run the pattern rules now and return the open cards */
    post: operations['observe_api_adaptations_observe_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations/{adaptation_id}/decide': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Try (this session) / Make default / No (ask in 14 days) / Don't suggest again */
    post: operations['decide_api_adaptations__adaptation_id__decide_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations/{adaptation_id}/undo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Revert an applied adaptation to the previous value (logged as undone) */
    post: operations['undo_api_adaptations__adaptation_id__undo_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations/log': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Adaptation log: every card and what happened to it */
    get: operations['log_api_adaptations_log_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Registry rows (defaults seeded, readiness refreshed) */
    get: operations['list_models_api_models_get']
    put?: never
    /** Add a registry row (nothing is downloaded yet) */
    post: operations['add_api_models_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search Hugging Face (GGUF / mlx-community filters) */
    get: operations['search_api_models_search_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/{registry_id}/pull': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Download in the background (status: downloading → ready) */
    post: operations['pull_api_models__registry_id__pull_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/{registry_id}/bench': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Benchmark in the background (tok/s, first token, tutoring checks) */
    post: operations['bench_api_models__registry_id__bench_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Background pull/bench jobs with their progress lines */
    get: operations['jobs_api_models_jobs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/{registry_id}/assign': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Route a TaskClass to this model for the owner (must be ready) */
    post: operations['assign_api_models__registry_id__assign_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/{registry_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove the artefact and mark the row removed */
    delete: operations['remove_api_models__registry_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/models/routing': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** TaskClass → chain with readiness; what each task will actually use */
    get: operations['routing_api_models_routing_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/experiments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Experiments, templates and available metrics */
    get: operations['list_experiments_api_experiments_get']
    put?: never
    /** Create an experiment by hand */
    post: operations['create_api_experiments_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/experiments/from-template': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create from a template (e.g. socratic-vs-explicit) */
    post: operations['from_template_api_experiments_from_template_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/experiments/{experiment_id}/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start: new units get assigned from now on */
    post: operations['start_api_experiments__experiment_id__start_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/experiments/{experiment_id}/stop': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Stop: freeze the window; results stay readable */
    post: operations['stop_api_experiments__experiment_id__stop_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/experiments/{experiment_id}/results': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Per-arm outcomes from the event log, read as hypotheses */
    get: operations['results_api_experiments__experiment_id__results_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/practice': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log a practice block (movement / guitar / language) as a practiced event */
    post: operations['log_api_practice_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/practice/activities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Concrete activity options per domain (2–3 choices) */
    get: operations['activities_api_practice_activities_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/vocab': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Vocabulary decks with card and due counts */
    get: operations['decks_api_vocab_get']
    put?: never
    /** Add a vocabulary card (FSRS-scheduled, reviewed in the language block) */
    post: operations['add_api_vocab_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ActivitiesOut */
    ActivitiesOut: {
      /** Activities */
      activities: {
        [key: string]: string[]
      }
    }
    /** AddIn */
    AddIn: {
      /** Source */
      source: string
      /** Repo Id */
      repo_id: string
      /** File */
      file?: string | null
      /** Tag */
      tag?: string | null
      /** Registry Id */
      registry_id?: string | null
      /** Display Name */
      display_name?: string | null
      /**
       * Role
       * @default chat
       */
      role: string
      /** Quant */
      quant?: string | null
      /** Context Len */
      context_len?: number | null
      /**
       * Price In
       * @default 0
       */
      price_in: number
      /**
       * Price Out
       * @default 0
       */
      price_out: number
    }
    /** ArmIn */
    ArmIn: {
      /** Name */
      name: string
      /** Config */
      config?: {
        [key: string]: unknown
      }
    }
    /** ArmOut */
    ArmOut: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Config */
      config: {
        [key: string]: unknown
      }
      /** Assigned */
      assigned: number
    }
    /** ArmStatsOut */
    ArmStatsOut: {
      /** Arm Id */
      arm_id: string
      /** Name */
      name: string
      /** N */
      n: number
      /** Mean */
      mean: number | null
      /** Sd */
      sd: number | null
    }
    /** AssessmentView */
    AssessmentView: {
      /** Id */
      id: string
      /** Skill Id */
      skill_id: string
      /** Kind */
      kind: string
      /** Question */
      question: string
      /** Options */
      options?: string[] | null
      /** Criteria */
      criteria?: string[] | null
      /**
       * Confidence Required
       * @default true
       */
      confidence_required: boolean
    }
    /** AssignIn */
    AssignIn: {
      /** Task */
      task: string
    }
    /** AttemptRequest */
    AttemptRequest: {
      /** Session Id */
      session_id: string
      /** Assessment Id */
      assessment_id: string
      /** Answer */
      answer: string
      /** Confidence Pre */
      confidence_pre: number
      /** Latency Ms */
      latency_ms?: number | null
      /**
       * Hint Count
       * @default 0
       */
      hint_count: number
    }
    /** AttemptResult */
    AttemptResult: {
      /** Attempt Id */
      attempt_id: string
      /** Assessment Id */
      assessment_id: string
      /** Skill Id */
      skill_id: string
      /** Kind */
      kind: string
      /** Dimension */
      dimension: string
      /** Correct */
      correct: boolean | null
      /** Score */
      score: number
      /** Criterion Results */
      criterion_results: components['schemas']['CriterionResult'][]
      /** Misconception */
      misconception: string | null
      /** Confidence */
      confidence: number
      /** Grader Level */
      grader_level: string
      /** Feedback */
      feedback: string
      /** Next Step */
      next_step: string
      /** Confidence Pre */
      confidence_pre: number
      /** Calibration */
      calibration: string
      /** Review */
      review: {
        [key: string]: unknown
      }
      /** Mastery */
      mastery: number
    }
    /** Block */
    Block: {
      /**
       * Type
       * @enum {string}
       */
      type:
        | 'movement_primer'
        | 'retrieval'
        | 'new_material'
        | 'challenge'
        | 'interleaved_review'
        | 'domain_switch'
        | 'recap'
      /** Planned Min */
      planned_min: number
      /** Node Ids */
      node_ids?: string[]
      /**
       * Optional
       * @default false
       */
      optional: boolean
      /**
       * Reason
       * @default
       */
      reason: string
      /**
       * Grasp Check Required
       * @default false
       */
      grasp_check_required: boolean
      /** Domain */
      domain?: string | null
    }
    /** BlockEvent */
    BlockEvent: {
      /** Session Id */
      session_id: string
      /** Index */
      index: number
      /** Actual Min */
      actual_min?: number | null
      /**
       * Switched Early
       * @default false
       */
      switched_early: boolean
      /** Reason */
      reason?: string | null
      /** Grasp Passed */
      grasp_passed?: boolean | null
    }
    /** BlockOut */
    BlockOut: {
      /** Index */
      index: number
      block: components['schemas']['Block']
      /** Allowed */
      allowed: boolean
      /** Message */
      message: string
      /** Next Index */
      next_index: number | null
    }
    /** ChainEntry */
    ChainEntry: {
      /** Registry Id */
      registry_id: string
      /** Status */
      status: string
    }
    /** ChallengeStart */
    ChallengeStart: {
      /** Session Id */
      session_id: string
      /**
       * Mode
       * @enum {string}
       */
      mode: 'planted_error' | 'steelman' | 'teach_back' | 'calibration'
      /** Skill Id */
      skill_id?: string | null
    }
    /** ChallengeView */
    ChallengeView: {
      /** Assessment Id */
      assessment_id: string
      /** Skill Id */
      skill_id: string
      /**
       * Mode
       * @enum {string}
       */
      mode: 'planted_error' | 'steelman' | 'teach_back' | 'calibration'
      /** Prompt */
      prompt: string
      /** Criteria */
      criteria: string[]
      /** Cached */
      cached: boolean
      /** Sources */
      sources: string[]
    }
    /** CheckpointIn */
    CheckpointIn: {
      /** Phase */
      phase?: string | null
      /** Skill Id */
      skill_id?: string | null
      /** Block Index */
      block_index?: number | null
      /** Extra */
      extra?: {
        [key: string]: unknown
      }
    }
    /** CorpusStats */
    CorpusStats: {
      retrieval: components['schemas']['RetrievalConfigOut']
      /** Documents */
      documents: number
      /** Versions */
      versions: number
      /** Chunks */
      chunks: number
      /** Flagged Chunks */
      flagged_chunks: number
      /** Courses */
      courses: components['schemas']['CourseStats'][]
      index: components['schemas']['IndexStateOut'] | null
      /**
       * Index Count
       * @description live count from the retrieval index
       */
      index_count?: number | null
    }
    /** CourseStats */
    CourseStats: {
      /** Course */
      course: string
      /** Documents */
      documents: number
      /** Chunks */
      chunks: number
      /** Flagged */
      flagged: number
      /** Source Types */
      source_types: string[]
      /** Trust Tiers */
      trust_tiers: number[]
    }
    /** CriterionResult */
    CriterionResult: {
      /** Criterion */
      criterion: string
      /** Passed */
      passed: boolean
      /**
       * Evidence
       * @default
       */
      evidence: string
    }
    /** DecideIn */
    DecideIn: {
      /**
       * Decision
       * @enum {string}
       */
      decision: 'try' | 'default' | 'no' | 'never'
      /** Session Id */
      session_id?: string | null
    }
    /** DeckList */
    DeckList: {
      /** Decks */
      decks: {
        [key: string]: unknown
      }[]
      /** Due Total */
      due_total: number
    }
    /** DocumentList */
    DocumentList: {
      /** Documents */
      documents: components['schemas']['DocumentOut'][]
    }
    /** DocumentOut */
    DocumentOut: {
      /** Id */
      id: string
      /** Title */
      title: string
      /** Source Type */
      source_type: string
      /** Uri */
      uri: string
      /** Course */
      course: string | null
      /** Section */
      section: string | null
      /** Lecture */
      lecture: string | null
      /** Version */
      version: number
      /** Chunks */
      chunks: number
      /** Flagged */
      flagged: number
      /** Trust Tier */
      trust_tier: number
      /** Ingested At */
      ingested_at: string | null
    }
    /** DueList */
    DueList: {
      /** Items */
      items: components['schemas']['ReviewItemOut'][]
      /** Cap */
      cap: number
      /** Total Due */
      total_due: number
      /** As Of */
      as_of: string
    }
    /** ExperimentIn */
    ExperimentIn: {
      /** Name */
      name: string
      /**
       * Hypothesis
       * @default
       */
      hypothesis: string
      /** Metric */
      metric: string
      /**
       * Unit Type
       * @default node
       */
      unit_type: string
      /** Arms */
      arms: components['schemas']['ArmIn'][]
    }
    /** ExperimentList */
    ExperimentList: {
      /** Experiments */
      experiments: components['schemas']['ExperimentOut'][]
      /** Templates */
      templates: {
        [key: string]: unknown
      }[]
      /** Metrics */
      metrics: string[]
    }
    /** ExperimentOut */
    ExperimentOut: {
      /** Id */
      id: string
      /** Name */
      name: string
      /** Hypothesis */
      hypothesis: string
      /** Metric */
      metric: string
      /** Unit Type */
      unit_type: string
      /** Status */
      status: string
      /** Created At */
      created_at: string
      /** Started At */
      started_at: string | null
      /** Ended At */
      ended_at: string | null
      /** Arms */
      arms: components['schemas']['ArmOut'][]
    }
    /** ForgetOut */
    ForgetOut: {
      /** Document Id */
      document_id: string
      /** Chunks Removed */
      chunks_removed: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** Health */
    Health: {
      /** Status */
      status: string
      /** Env */
      env: string
      /** Db */
      db: string
    }
    /** HfSearchHit */
    HfSearchHit: {
      /** Repo Id */
      repo_id: string
      /** Downloads */
      downloads: number | null
      /** Likes */
      likes: number | null
      /** Tags */
      tags: string[]
    }
    /** HfSearchOut */
    HfSearchOut: {
      /** Hits */
      hits: components['schemas']['HfSearchHit'][]
    }
    /** HistoryList */
    HistoryList: {
      /** Entries */
      entries: components['schemas']['HistoryOut'][]
    }
    /** HistoryOut */
    HistoryOut: {
      /** Id */
      id: string
      /** What */
      what: string
      /** Why */
      why: string
      /** Origin */
      origin: string
      /** Pattern */
      pattern: string
      /** Pref */
      pref: string
      /** Value */
      value: unknown
      /** Previous */
      previous: unknown | null
      /** Proposed At */
      proposed_at: string
      /** Decision */
      decision: string | null
      /** Decided At */
      decided_at: string | null
      /** Undone At */
      undone_at: string | null
      /** In Effect */
      in_effect: boolean
      /** Trial */
      trial: boolean
    }
    /** IndexStateOut */
    IndexStateOut: {
      /** Collection */
      collection: string
      /** Embedding Registry Id */
      embedding_registry_id: string
      /** Embedding Version */
      embedding_version: number
      /** Dims */
      dims: number
      /** Chunk Count */
      chunk_count: number
      /** Last Reindex */
      last_reindex: string | null
    }
    /** IngestDocResult */
    IngestDocResult: {
      /** Document Id */
      document_id: string
      /** Title */
      title: string
      /** Course */
      course: string | null
      /** Source Type */
      source_type: string
      /** Version */
      version: number
      /** Chunks */
      chunks: number
      /** Changed */
      changed: boolean
      /** Deduped */
      deduped: number
      /** Flagged */
      flagged: number
      /** Indexed */
      indexed: number
      /**
       * Trust Updated
       * @default false
       */
      trust_updated: boolean
      /**
       * Reverted
       * @default false
       */
      reverted: boolean
    }
    /** IngestOut */
    IngestOut: {
      /** Summary */
      summary: {
        [key: string]: unknown
      }
      /** Results */
      results: components['schemas']['IngestDocResult'][]
      /** Skipped */
      skipped: components['schemas']['SkippedFile'][]
    }
    /** IngestRequest */
    IngestRequest: {
      /**
       * Path
       * @description local file or folder (Udemy layout: Course/Section/Lecture)
       */
      path: string
      /** Course */
      course?: string | null
      /**
       * Trust Tier
       * @default 2
       */
      trust_tier: number
      /** Source Type */
      source_type?: string | null
      /**
       * Index
       * @default true
       */
      index: boolean
    }
    /** JobList */
    JobList: {
      /** Jobs */
      jobs: components['schemas']['JobOut'][]
    }
    /** JobOut */
    JobOut: {
      /** Id */
      id: string
      /** Kind */
      kind: string
      /** Registry Id */
      registry_id: string
      /** Status */
      status: string
      /** Log */
      log?: string[]
      /** Error */
      error?: string | null
      /** Result */
      result?: {
        [key: string]: unknown
      } | null
    }
    /** KindsOut */
    KindsOut: {
      /** Object Id */
      object_id: string
      /** Concept */
      concept: string
      /** Kinds */
      kinds: {
        [key: string]: unknown
      }[]
    }
    /** LearnerOut */
    LearnerOut: {
      /** Id */
      id: string
      /** Display Name */
      display_name: string
      /** Created At */
      created_at: string
    }
    /** MapOut */
    MapOut: {
      /** Nodes */
      nodes: {
        [key: string]: unknown
      }[]
      /** Edges */
      edges: {
        [key: string]: unknown
      }[]
      /** Mermaid */
      mermaid: string
    }
    /** MetricOut */
    MetricOut: {
      /** Metric */
      metric: string
      /** Lower Is Better */
      lower_is_better: boolean
      /** Arms */
      arms: components['schemas']['ArmStatsOut'][]
      /** Difference */
      difference: number | null
      /** Ci95 */
      ci95: number[] | null
      /** Reading */
      reading: string
    }
    /**
     * Mode
     * @enum {string}
     */
    Mode: 'novelty' | 'steady' | 'low_capacity'
    /** ModelList */
    ModelList: {
      /** Models */
      models: components['schemas']['ModelRow'][]
    }
    /** ModelRow */
    ModelRow: {
      /** Id */
      id: string
      /** Display Name */
      display_name: string
      /** Source */
      source: string
      /** Repo Id */
      repo_id: string
      /** File Or Tag */
      file_or_tag: string | null
      /** Runtime */
      runtime: string
      /** Role */
      role: string
      /** Quant */
      quant: string | null
      /** Size Gb */
      size_gb: number | null
      /** Context Len */
      context_len: number | null
      /** Licence */
      licence: string | null
      /** Status */
      status: string
      /** Benchmark */
      benchmark: {
        [key: string]: unknown
      } | null
      /** Price In Per Mtok */
      price_in_per_mtok: number
      /** Price Out Per Mtok */
      price_out_per_mtok: number
      /** Local Path */
      local_path: string | null
      /** Updated At */
      updated_at: string
    }
    /** ModesOut */
    ModesOut: {
      /** Modes */
      modes: {
        [key: string]: string
      }[]
    }
    /** NextItem */
    NextItem: {
      item: components['schemas']['AssessmentView'] | null
      /** Skill Id */
      skill_id: string
    }
    /** ParkIn */
    ParkIn: {
      /** Session Id */
      session_id?: string | null
      /** Text */
      text: string
      /** Node Id */
      node_id?: string | null
    }
    /** ParkList */
    ParkList: {
      /** Items */
      items: components['schemas']['ParkOut'][]
    }
    /** ParkOut */
    ParkOut: {
      /** Id */
      id: string
      /** Text */
      text: string
      /** Node Id */
      node_id: string | null
      /** Status */
      status: string
      /** Promoted To */
      promoted_to?: string | null
      /** Created At */
      created_at: string
    }
    /** Plan */
    Plan: {
      /** Mode */
      mode: string
      /** Energy */
      energy: number
      /** Blocks */
      blocks: components['schemas']['Block'][]
      /** Minimum Viable */
      minimum_viable: string[]
      /** Total Min */
      total_min: number
      /**
       * Policy Version
       * @default planner.v1
       */
      policy_version: string
    }
    /** PracticeIn */
    PracticeIn: {
      /** Session Id */
      session_id?: string | null
      /** Domain */
      domain: string
      /** Activity */
      activity: string
      /** Duration Min */
      duration_min: number
      /** Self Rating */
      self_rating: number
      /** Notes */
      notes?: string | null
    }
    /** PracticeOut */
    PracticeOut: {
      /** Event Id */
      event_id: string
      /** Domain */
      domain: string
      /** Activity */
      activity: string
      /** Duration Min */
      duration_min: number
      /** Self Rating */
      self_rating: number
    }
    /** PrefOut */
    PrefOut: {
      /** Values */
      values: {
        [key: string]: unknown
      }
      /** Specs */
      specs: {
        [key: string]: unknown
      }[]
    }
    /** PrefSet */
    PrefSet: {
      /** Key */
      key: string
      /** Value */
      value: unknown
      /**
       * Origin
       * @default explicit
       */
      origin: string
    }
    /** PreferIn */
    PreferIn: {
      /** Session Id */
      session_id: string
      /** Chosen Id */
      chosen_id: string
      /** Rejected Id */
      rejected_id: string
      /** Reason */
      reason?: string | null
    }
    /** PromoteIn */
    PromoteIn: {
      /**
       * Promoted To
       * @description 'next_session' (shown on Home until done) or a skill node id
       * @default next_session
       */
      promoted_to: string
    }
    /** ProposalList */
    ProposalList: {
      /** Proposals */
      proposals: components['schemas']['ProposalOut'][]
    }
    /** ProposalOut */
    ProposalOut: {
      /** Id */
      id: string
      /** What */
      what: string
      /** Why */
      why: string
      /** Origin */
      origin: string
      /** Pattern */
      pattern: string
      /** Pref */
      pref: string
      /** Value */
      value: unknown
      /** Evidence */
      evidence: {
        [key: string]: unknown
      }
      /** Proposed At */
      proposed_at: string
      /** Reversible */
      reversible: boolean
    }
    /** RenderIn */
    RenderIn: {
      /** Session Id */
      session_id: string
      /**
       * Force
       * @default false
       */
      force: boolean
    }
    /** RenderOut */
    RenderOut: {
      /** Object Id */
      object_id: string
      /** Skill Id */
      skill_id: string
      /** Concept */
      concept: string
      /** Kind */
      kind: string
      /** Content */
      content: string
      /** Representation Id */
      representation_id: string
      /** Model Call Id */
      model_call_id: string | null
      /** Cached */
      cached: boolean
      /** Sources */
      sources: string[]
    }
    /** ReplanIn */
    ReplanIn: {
      /** Session Id */
      session_id: string
      /** Energy */
      energy: number
      /**
       * From Index
       * @description first block that may change
       * @default 0
       */
      from_index: number
    }
    /** ReplanOut */
    ReplanOut: {
      /** Proposal Id */
      proposal_id: string | null
      /** Energy */
      energy: number
      plan: components['schemas']['Plan']
      /** Changed */
      changed: boolean
    }
    /** ResultsOut */
    ResultsOut: {
      experiment: components['schemas']['ExperimentOut']
      /** Primary Metric */
      primary_metric: string
      /** Metrics */
      metrics: components['schemas']['MetricOut'][]
      /** Units */
      units: {
        [key: string]: unknown
      }[]
    }
    /** RetierRequest */
    RetierRequest: {
      /** Trust Tier */
      trust_tier: number
    }
    /** RetrievalConfigOut */
    RetrievalConfigOut: {
      /** Collection */
      collection: string
      /**
       * Reranker
       * @description registry model used after fusion
       */
      reranker?: string | null
      /** Max Per Document */
      max_per_document: number
    }
    /** ReviewItemOut */
    ReviewItemOut: {
      /** Item Id */
      item_id: string
      /** Skill Id */
      skill_id: string
      /** Skill Title */
      skill_title: string
      /** Item Type */
      item_type: string
      /** Question */
      question: string
      /** Options */
      options: string[] | null
      /** Reveal */
      reveal: string
      /** Due */
      due: string
      /** State */
      state: string
    }
    /** ReviewOut */
    ReviewOut: {
      /** Item Id */
      item_id: string
      /** Due */
      due: string
      /** State */
      state: string
      /** Stability */
      stability: number | null
      /** Predicted Retrievability */
      predicted_retrievability: number | null
    }
    /** ReviewRating */
    ReviewRating: {
      /** Session Id */
      session_id: string
      /** Rating */
      rating: number
      /** Confidence Pre */
      confidence_pre?: number | null
      /** Latency Ms */
      latency_ms?: number | null
    }
    /** RouteRow */
    RouteRow: {
      /** Task */
      task: string
      /** Override */
      override: string | null
      /** Chain */
      chain: components['schemas']['ChainEntry'][]
      /** Resolved */
      resolved: string | null
    }
    /** RoutingOut */
    RoutingOut: {
      /** Profile */
      profile: string
      /** Routes */
      routes: components['schemas']['RouteRow'][]
    }
    /** SearchHit */
    SearchHit: {
      /** Chunk Id */
      chunk_id: string
      /** Rank */
      rank: number
      /** Score */
      score: number
      /** Dense Score */
      dense_score: number | null
      /** Sparse Score */
      sparse_score: number | null
      /** Rerank Score */
      rerank_score?: number | null
      /** Citation */
      citation: string
      /** Course */
      course: string | null
      /** Section */
      section: string | null
      /** Lecture */
      lecture: string | null
      /** Source Type */
      source_type: string
      /** Trust Tier */
      trust_tier: number
      /** T Start */
      t_start: number | null
      /** Flagged */
      flagged: string[]
      /**
       * Quarantined
       * @default false
       */
      quarantined: boolean
      /** Text */
      text: string
    }
    /** SearchOut */
    SearchOut: {
      /** Query */
      query: string
      /** Hits */
      hits: components['schemas']['SearchHit'][]
      /** Latency Ms */
      latency_ms: number
      /** Reranked */
      reranked: boolean
      /** Flagged Patterns */
      flagged_patterns: string[]
      /** Collection */
      collection: string
    }
    /** SearchRequest */
    SearchRequest: {
      /** Query */
      query: string
      /**
       * K
       * @default 8
       */
      k: number
      /** Course */
      course?: string | null
      /** Section */
      section?: string | null
      /** Lecture */
      lecture?: string | null
      /** Source Type */
      source_type?: string | null
      /** Skill Ids */
      skill_ids?: string[] | null
      /** Min Trust Tier */
      min_trust_tier?: number | null
      /**
       * Tutor View
       * @description apply the tutor's trust floor and mark quarantined hits
       * @default false
       */
      tutor_view: boolean
    }
    /** SessionEnd */
    SessionEnd: {
      /** Energy After */
      energy_after: number
      /** Self Report */
      self_report: number
      /** Notes */
      notes?: string | null
    }
    /** SessionOut */
    SessionOut: {
      /** Id */
      id: string
      /** Mode */
      mode: string
      /** Energy */
      energy: number
      /** Socratic */
      socratic: boolean
      /** Started At */
      started_at: string
      /** Ended At */
      ended_at: string | null
      /** Energy After */
      energy_after: number | null
      next_skill: components['schemas']['SkillView'] | null
      /** Due Reviews */
      due_reviews: number
      /** Review Cap */
      review_cap: number
      /** Minimum Viable */
      minimum_viable: string[]
      /** Plan */
      plan: {
        [key: string]: unknown
      }[]
      /** Checkpoint */
      checkpoint: {
        [key: string]: unknown
      } | null
      /** Experiment */
      experiment?: {
        [key: string]: unknown
      } | null
    }
    /** SessionStart */
    SessionStart: {
      /** @default steady */
      mode: components['schemas']['Mode']
      /**
       * Energy
       * @default 3
       */
      energy: number
      /**
       * Socratic
       * @default false
       */
      socratic: boolean
    }
    /** SkillList */
    SkillList: {
      /** Skills */
      skills: components['schemas']['SkillView'][]
      /** Next Skill Id */
      next_skill_id: string | null
    }
    /** SkillView */
    SkillView: {
      /** Id */
      id: string
      /** Slug */
      slug: string
      /** Title */
      title: string
      /** Description */
      description: string
      /** Domain */
      domain: string
      /** Success Criteria */
      success_criteria: string[]
      /** Prerequisites */
      prerequisites: string[]
      /** Mastery */
      mastery: number
      /** Unlocked */
      unlocked: boolean
      /** State */
      state: {
        [key: string]: unknown
      }
    }
    /** SkippedFile */
    SkippedFile: {
      /** Path */
      path: string
      /** Reason */
      reason: string
    }
    /** SourceRef */
    SourceRef: {
      /** Chunk Id */
      chunk_id: string
      /** Citation */
      citation: string
      /** Trust Tier */
      trust_tier: number
      /** Score */
      score: number
      /** Flagged */
      flagged?: string[]
      /**
       * Cited
       * @default false
       */
      cited: boolean
    }
    /** TemplateIn */
    TemplateIn: {
      /** Template */
      template: string
    }
    /** TurnDone */
    TurnDone: {
      /** Turn Id */
      turn_id: string
      /** Model Call Id */
      model_call_id: string | null
      /** Tutor Trace Id */
      tutor_trace_id: string
      /** Registry Id */
      registry_id: string | null
      /** Route */
      route: string | null
      /** Sentences */
      sentences: number
      /** Representation */
      representation: string | null
      /** Sources */
      sources: components['schemas']['SourceRef'][]
      /** Flagged */
      flagged: string[]
      /** Dropped */
      dropped: string[]
      /** Latency Ms */
      latency_ms: number
      /** Text */
      text: string
    }
    /** TurnRequest */
    TurnRequest: {
      /** Session Id */
      session_id: string
      /** Text */
      text: string
      /** Skill Id */
      skill_id?: string | null
      /**
       * Action
       * @default auto
       * @enum {string}
       */
      action: 'auto' | 'explain' | 'hint' | 'summarize' | 'full_solution'
      /** Representation */
      representation?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** VocabIn */
    VocabIn: {
      /** Lang */
      lang: string
      /** Word */
      word: string
      /** Translation */
      translation: string
      /** Example */
      example?: string | null
    }
    /** VocabItemOut */
    VocabItemOut: {
      /** Item Id */
      item_id: string
      /** Lang */
      lang: string
      /** Word */
      word: string
      /** Translation */
      translation: string
      /** Due */
      due: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  me_api_learner_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LearnerOut']
        }
      }
    }
  }
  list_skills_api_skills_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SkillList']
        }
      }
    }
  }
  skill_map_api_skills_map_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MapOut']
        }
      }
    }
  }
  get_skill_api_skills__skill_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        skill_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SkillView']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_api_sessions_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SessionStart']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  current_api_sessions_current_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionOut'] | null
        }
      }
    }
  }
  checkpoint_api_sessions__session_id__checkpoint_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CheckpointIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_api_sessions__session_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  end_api_sessions__session_id__end_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SessionEnd']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  preview_api_plan_preview_get: {
    parameters: {
      query?: {
        mode?: string
        energy?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Plan']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_block_api_plan_blocks_start_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BlockEvent']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BlockOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  end_block_api_plan_blocks_end_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BlockEvent']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BlockOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  replan_api_plan_replan_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReplanIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReplanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_all_api_preferences_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PrefOut']
        }
      }
    }
  }
  set_one_api_preferences_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PrefSet']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PrefOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reset_api_preferences__key__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PrefOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  kinds_api_objects__skill_id__representations_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        skill_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['KindsOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  prefer_api_objects__skill_id__representations_prefer_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        skill_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PreferIn']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  render_api_objects__skill_id__representations__kind__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        skill_id: string
        kind: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RenderIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RenderOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  modes_api_challenge_modes_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModesOut']
        }
      }
    }
  }
  start_api_challenge_start_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChallengeStart']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChallengeView']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_api_challenge_submit_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AttemptRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AttemptResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stream_api_tutor_stream_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TurnRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  turn_api_tutor_turn_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TurnRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TurnDone']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  next_item_api_assess_next_get: {
    parameters: {
      query: {
        session_id: string
        skill_id?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NextItem']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  attempt_api_assess_attempt_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AttemptRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AttemptResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  due_api_review_due_get: {
    parameters: {
      query: {
        session_id: string
        /** @description ISO time; dev/benchmark time travel */
        as_of?: string | null
        /** @description Undo the minimum-viable cap for this call */
        all?: boolean
        /** @description only this domain (e.g. language); default: all but language */
        domain?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DueList']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  rate_api_review__item_id__post: {
    parameters: {
      query?: {
        as_of?: string | null
      }
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewRating']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReviewOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_parked_api_parking_get: {
    parameters: {
      query?: {
        status?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ParkList']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  park_api_parking_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ParkIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ParkOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  promote_api_parking__item_id__promote_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PromoteIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ParkOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  drop_api_parking__item_id__drop_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        item_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ParkOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stats_api_corpus_stats_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CorpusStats']
        }
      }
    }
  }
  documents_api_corpus_documents_get: {
    parameters: {
      query?: {
        course?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentList']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  ingest_api_corpus_ingest_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IngestRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  forget_api_corpus_documents__document_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        document_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ForgetOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  retier_api_corpus_documents__document_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        document_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RetierRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_api_corpus_search_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SearchRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SearchOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  pending_api_adaptations_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProposalList']
        }
      }
    }
  }
  observe_api_adaptations_observe_post: {
    parameters: {
      query?: {
        session_id?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProposalList']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  decide_api_adaptations__adaptation_id__decide_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        adaptation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DecideIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HistoryList']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  undo_api_adaptations__adaptation_id__undo_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        adaptation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HistoryList']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  log_api_adaptations_log_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HistoryList']
        }
      }
    }
  }
  list_models_api_models_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelList']
        }
      }
    }
  }
  add_api_models_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AddIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelRow']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_api_models_search_get: {
    parameters: {
      query: {
        q: string
        gguf?: boolean
        mlx?: boolean
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HfSearchOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  pull_api_models__registry_id__pull_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        registry_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  bench_api_models__registry_id__bench_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        registry_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  jobs_api_models_jobs_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobList']
        }
      }
    }
  }
  assign_api_models__registry_id__assign_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        registry_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AssignIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoutingOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  remove_api_models__registry_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        registry_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelRow']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  routing_api_models_routing_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoutingOut']
        }
      }
    }
  }
  list_experiments_api_experiments_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExperimentList']
        }
      }
    }
  }
  create_api_experiments_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ExperimentIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExperimentOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  from_template_api_experiments_from_template_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TemplateIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExperimentOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_api_experiments__experiment_id__start_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        experiment_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExperimentOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stop_api_experiments__experiment_id__stop_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        experiment_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExperimentOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  results_api_experiments__experiment_id__results_get: {
    parameters: {
      query?: {
        record?: boolean
      }
      header?: never
      path: {
        experiment_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResultsOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  log_api_practice_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PracticeIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PracticeOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  activities_api_practice_activities_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivitiesOut']
        }
      }
    }
  }
  decks_api_vocab_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DeckList']
        }
      }
    }
  }
  add_api_vocab_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VocabIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VocabItemOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
